-- Fallstudie DLBITOWAWBI01 - Projekt- und Aufgabenmanagementsystem
-- Basisschema. Jede fachliche Tabelle traegt eine tenant_id; damit ist die
-- Anwendung mandantenfaehig vorbereitet, ohne bereits mehrere Mandanten
-- im Betrieb zu fuehren.

CREATE TABLE tenant (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT       NOT NULL REFERENCES tenant (id),
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name    VARCHAR(255) NOT NULL,
    last_name     VARCHAR(255) NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE user_role (
    user_id BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    role    VARCHAR(32) NOT NULL,
    PRIMARY KEY (user_id, role)
);

CREATE TABLE project (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL REFERENCES tenant (id),
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    status      VARCHAR(32)  NOT NULL,
    start_date  DATE,
    end_date    DATE,
    created_at  TIMESTAMP    NOT NULL
);

CREATE TABLE project_membership (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT NOT NULL REFERENCES tenant (id),
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_membership UNIQUE (project_id, user_id)
);

CREATE TABLE task (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL REFERENCES tenant (id),
    project_id  BIGINT       NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    status      VARCHAR(32)  NOT NULL,
    assignee_id BIGINT REFERENCES app_user (id),
    due_date    DATE,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL
);
